name    'nix-fw'
version '0.1.0'
author 'Artem Kobrin'
license 'GNU Library Public License, Version 2.1'
source 'https://github.com/puppetnix/fw'
summary 'Firewall module'
description 'Firewall module'
dependency 'puppetlabs/firewall', ''
